# Generated by Django 3.2.7 on 2021-09-07 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255)),
                ('bairro', models.CharField(choices=[('SP', 'São Paulo'), ('SC', 'Santa Catarina'), ('RJ', 'Rio de Janeiro')], default='SP', max_length=2)),
                ('numero', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.PositiveIntegerField()),
                ('cpf', models.CharField(max_length=14)),
                ('enderecos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.endereco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
