# Generated by Django 3.2.7 on 2021-09-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_perfil_enderecos'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='estado',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('SC', 'Santa Catarina'), ('RJ', 'Rio de Janeiro')], default='SP', max_length=2),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil'),
        ),
    ]
