# Generated by Django 3.2.7 on 2021-09-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_auto_20210907_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='user',
            new_name='perfil',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='bairro',
        ),
    ]
