# Generated by Django 3.2.7 on 2021-09-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lojas',
            options={'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
        migrations.AddField(
            model_name='lojas',
            name='celular',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='lojas',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lojas',
            name='rua',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
