# Generated by Django 3.2.7 on 2021-09-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_auto_20210908_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojas',
            name='celular',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lojas',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lojas',
            name='rua',
            field=models.CharField(max_length=255),
        ),
    ]
