# Generated by Django 3.2.7 on 2021-09-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sabor', models.CharField(max_length=100)),
                ('descricao_sabor', models.CharField(max_length=100)),
                ('preco_grande', models.FloatField()),
                ('preco_medio', models.FloatField()),
                ('preco_pequeno', models.FloatField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='sabores/')),
            ],
        ),
    ]
