# Generated by Django 3.2.7 on 2021-09-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabor',
            name='no_cardapio',
            field=models.BooleanField(default=True),
        ),
    ]
