# Generated by Django 3.2.7 on 2021-09-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0005_auto_20210908_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sabor',
            name='nome_sabor',
            field=models.CharField(max_length=100, unique=True, verbose_name='nome do sabor'),
        ),
    ]
