# Generated by Django 3.2.7 on 2021-09-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20210908_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
