# Generated by Django 3.2.7 on 2021-09-11 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_auto_20210911_1058'),
        ('pedido', '0006_auto_20210908_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='preco_grande',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='preco_medio',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='preco_pequeno',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='sabor_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='finalizado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pedindo'), ('R', 'Realizado'), ('F', 'Finalizado')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='perfil_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil', verbose_name='Cliente'),
        ),
    ]
