# Generated by Django 3.2.7 on 2021-09-30 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_auto_20210911_1058'),
        ('pedido', '0009_remove_pedido_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.endereco', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pronto'), ('S', 'Sendo Entregue'), ('F', 'Finalizado')], default='P', max_length=2),
        ),
    ]
