# Generated by Django 3.2.7 on 2021-10-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0010_auto_20210930_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(default='', max_length=255),
        ),
    ]
