# Generated by Django 3.2.7 on 2021-10-03 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_auto_20211003_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 3, 12, 43, 49, 257230)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Preparando'), ('E', 'Enviado'), ('R', 'Recebido')], default='P', max_length=2),
        ),
    ]
